spring:
    main:
        allow-bean-definition-overriding: true
    application:
        name: ATC-BE-MONTECARLO-SERVICE
    data:
        redis:
            host: localhost
            port: 6379
        mongodb:
            uri: mongodb://localhost:27017
            database: atc
server:
    port: 5002