spring:
    application:
        name: ATC-BE-MONTECARLO-SERVICE
    data:
        redis:
            host: localhost
            port: 6379
        mongodb:
            uri:
            database: atc
server:
    port: 5002